// Solo se conecta al clúster efímero verificado de db:test.
const assert = require('node:assert/strict'),
  fs = require('node:fs/promises'),
  path = require('node:path')
const { randomUUID } = require('node:crypto'),
  { Client } = require('pg'),
  { load, root } = require('./loader.cjs')
const { BaseLocal } = load(root + '/src/main/database/base.ts')
const { insertarRendimiento } = require('../scripts/seed-rendimiento-core.cjs')
const { verificarEquivalencia } = require('../scripts/verificar-etapa04.cjs')
async function main() {
  const archivo = path.resolve(process.argv[2]),
    carpeta = path.dirname(archivo)
  assert.match(path.basename(carpeta), /^ruizcacao-tests-/)
  const config = JSON.parse(await fs.readFile(archivo, 'utf8')),
    admin = new Client(config)
  await admin.connect()
  const real = (await admin.query('SHOW data_directory')).rows[0].data_directory
  assert.equal(
    (await fs.realpath(real)).toLowerCase(),
    (await fs.realpath(path.join(carpeta, 'motor', 'data'))).toLowerCase()
  )
  const nombre = 'rcm_listados_' + randomUUID().replaceAll('-', '')
  let base,
    creada = false
  try {
    await admin.query('CREATE DATABASE "' + nombre + '"')
    creada = true
    base = new BaseLocal({ ...config, database: nombre })
    await base.iniciar()
    for (const metodo of [
      'historialCombinado',
      'listadoGastos',
      'resumenGastos',
      'reportePeriodo',
      'documentoReporte'
    ])
      await assert.rejects(base[metodo]({}, 'diario'), /Inicia sesión/)
    await base.crearAdministrador('Listados', 'Listados-seguro-2026!')
    await base.login('Listados', 'Listados-seguro-2026!')
    const db = await base.pool.connect()
    try {
      await insertarRendimiento(db, {
        clientes: 15,
        proveedores: 10,
        compras: 120,
        ventas: 150,
        gastos: 120
      })
      // Abonos de una cuenta anulada deben excluirse; preserva todo su historial.
      await db.query(
        "UPDATE ruizcacao.cuentas SET estado='anulado' WHERE id=(SELECT cuenta_id FROM ruizcacao.movimientos_cuenta ORDER BY orden LIMIT 1)"
      )
      // Contrato histórico: reportes usa categoría de cuenta; Gastos usa la del movimiento.
      await db.query(
        "UPDATE ruizcacao.movimientos_cuenta SET categoria='compra' WHERE id=(SELECT m.id FROM ruizcacao.movimientos_cuenta m JOIN ruizcacao.cuentas c ON c.id=m.cuenta_id WHERE c.categoria='venta' ORDER BY m.orden LIMIT 1)"
      )
      await db.query(
        "UPDATE ruizcacao.gastos SET observacion='ÁRBOL %_ Ñ ΣΊΓΜΑ',empleado_nombre='Peña' WHERE tipo='manual'"
      )
      const estado = (await base.cargar()).datos
      const r = await verificarEquivalencia(db, estado, { completo: false })
      assert.equal(r.finanzas.length, 5)
      // Todas las variantes de filtros inválidos deben rechazarse sin llegar a SQL.
      for (const metodo of ['historialCombinado', 'listadoGastos', 'reportePeriodo'])
        for (const filtro of [
          null,
          [],
          { limite: 1000 },
          { desde: '2026-02-30' },
          { desde: '2026-02-01', hasta: '2026-01-01' },
          { cursor: 'no-json' },
          { desconocido: 1 }
        ])
          await assert.rejects(base[metodo](filtro))
      const p = await base.historialCombinado({ limite: 10 })
      const cursor = JSON.parse(Buffer.from(p.siguiente, 'base64url').toString('utf8'))
      assert.equal(typeof cursor.clave[0], 'string')
      for (const filtro of [
        { tipo: 'venta' },
        { busqueda: 'peña' },
        { estado: 'parcial' },
        { limite: 50 }
      ])
        await assert.rejects(base.historialCombinado({ ...filtro, cursor: p.siguiente }))
      await assert.rejects(base.listadoGastos({ cursor: p.siguiente }))
      // Actualizar órdenes a BIGINT >2^53 y empatar posiciones no puede perder filas.
      await db.query('ALTER TABLE ruizcacao.cuentas ALTER COLUMN orden SET GENERATED BY DEFAULT')
      await db.query('UPDATE ruizcacao.cuentas SET orden=9007199254740993+orden')
      const q = await base.historialCombinado({ limite: 50 })
      assert.ok(
        BigInt(JSON.parse(Buffer.from(q.siguiente, 'base64url')).clave[0]) > 9007199254740991n
      )
      const siguiente = await base.historialCombinado({ limite: 50, cursor: q.siguiente })
      assert.equal(new Set([...q.filas, ...siguiente.filas].map((c) => c.id)).size, 100)
      assert.deepEqual(
        (await base.cargar()).datos.cuentas.map((c) => c.id),
        estado.cuentas.map((c) => c.id)
      )
      console.log(
        'OK listados: COUNT/filtros/10-15-25-50/cursor BIGINT/Unicode/anulados/resúmenes completos/equivalencia de filas y HTML PDF diario-semanal-mensual.'
      )
    } finally {
      db.release()
    }
  } finally {
    await base?.cerrar()
    if (creada) await admin.query('DROP DATABASE "' + nombre + '" WITH (FORCE)')
    await admin.end()
  }
}
main().catch((e) => {
  console.error(e.stack)
  process.exitCode = 1
})
