-- Referencia de la migración histórica 1; la aplicación controla su ejecución.
CREATE SCHEMA IF NOT EXISTS ruizcacao;
CREATE TABLE IF NOT EXISTS ruizcacao.migraciones(version integer PRIMARY KEY, aplicada_en timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS ruizcacao.administrador(id integer PRIMARY KEY CHECK(id=1), nombre text NOT NULL, password_hash text NOT NULL, recovery_hash text NOT NULL, fallos integer NOT NULL DEFAULT 0, bloqueado_hasta timestamptz, actualizado_en timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS ruizcacao.sesiones(id uuid PRIMARY KEY, iniciada_en timestamptz NOT NULL DEFAULT now(), cerrada_en timestamptz, cierre text);
CREATE TABLE IF NOT EXISTS ruizcacao.jornadas(fecha date PRIMARY KEY, estado text NOT NULL CHECK(estado IN ('activa','finalizada')), apertura timestamptz NOT NULL DEFAULT now(), cierre timestamptz);
CREATE UNIQUE INDEX IF NOT EXISTS jornada_activa_unica ON ruizcacao.jornadas ((estado)) WHERE estado='activa';
CREATE TABLE IF NOT EXISTS ruizcacao.eventos_jornada(id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY, fecha_jornada date NOT NULL REFERENCES ruizcacao.jornadas(fecha), accion text NOT NULL, responsable text NOT NULL, fecha timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS ruizcacao.notificaciones(id uuid PRIMARY KEY, titulo text NOT NULL, mensaje text NOT NULL, fecha timestamptz NOT NULL DEFAULT now(), leida boolean NOT NULL DEFAULT false);
CREATE TABLE IF NOT EXISTS ruizcacao.configuracion(id integer PRIMARY KEY CHECK(id=1), datos jsonb NOT NULL);
CREATE TABLE IF NOT EXISTS ruizcacao.operaciones(id uuid PRIMARY KEY, comando text NOT NULL, firma text NOT NULL, resultado jsonb, creado_en timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS ruizcacao.auditoria(id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY, accion text NOT NULL, responsable text NOT NULL, detalle jsonb NOT NULL DEFAULT '{}', fecha timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS ruizcacao.clientes(id text PRIMARY KEY, datos jsonb NOT NULL CHECK(jsonb_typeof(datos)='object' AND datos->>'id'=id), orden bigint GENERATED ALWAYS AS IDENTITY, actualizado_en timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS ruizcacao.proveedores(id text PRIMARY KEY, datos jsonb NOT NULL CHECK(jsonb_typeof(datos)='object' AND datos->>'id'=id), orden bigint GENERATED ALWAYS AS IDENTITY, actualizado_en timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS ruizcacao.empleados(id text PRIMARY KEY, datos jsonb NOT NULL CHECK(jsonb_typeof(datos)='object' AND datos->>'id'=id), orden bigint GENERATED ALWAYS AS IDENTITY, actualizado_en timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS ruizcacao.compras(id text PRIMARY KEY, datos jsonb NOT NULL CHECK(jsonb_typeof(datos)='object' AND datos->>'id'=id), orden bigint GENERATED ALWAYS AS IDENTITY, actualizado_en timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS ruizcacao.ventas(id text PRIMARY KEY, datos jsonb NOT NULL CHECK(jsonb_typeof(datos)='object' AND datos->>'id'=id), orden bigint GENERATED ALWAYS AS IDENTITY, actualizado_en timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS ruizcacao.cuentas(id text PRIMARY KEY, datos jsonb NOT NULL CHECK(jsonb_typeof(datos)='object' AND datos->>'id'=id), orden bigint GENERATED ALWAYS AS IDENTITY, actualizado_en timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS ruizcacao.movimientos_cuenta(id text PRIMARY KEY, datos jsonb NOT NULL CHECK(jsonb_typeof(datos)='object' AND datos->>'id'=id), orden bigint GENERATED ALWAYS AS IDENTITY, actualizado_en timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS ruizcacao.movimientos_stock(id text PRIMARY KEY, datos jsonb NOT NULL CHECK(jsonb_typeof(datos)='object' AND datos->>'id'=id), orden bigint GENERATED ALWAYS AS IDENTITY, actualizado_en timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS ruizcacao.gastos(id text PRIMARY KEY, datos jsonb NOT NULL CHECK(jsonb_typeof(datos)='object' AND datos->>'id'=id), orden bigint GENERATED ALWAYS AS IDENTITY, actualizado_en timestamptz NOT NULL DEFAULT now());
ALTER TABLE ruizcacao.compras ADD COLUMN proveedor_id text GENERATED ALWAYS AS (datos->>'proveedorId') STORED REFERENCES ruizcacao.proveedores(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ruizcacao.ventas ADD COLUMN cliente_id text GENERATED ALWAYS AS (datos->>'clienteId') STORED REFERENCES ruizcacao.clientes(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ruizcacao.cuentas ADD COLUMN cliente_id text GENERATED ALWAYS AS (nullif(datos->>'clienteId','')) STORED REFERENCES ruizcacao.clientes(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ruizcacao.cuentas ADD COLUMN proveedor_id text GENERATED ALWAYS AS (datos->>'proveedorId') STORED REFERENCES ruizcacao.proveedores(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ruizcacao.cuentas ADD COLUMN compra_id text GENERATED ALWAYS AS (datos->>'compraId') STORED REFERENCES ruizcacao.compras(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ruizcacao.cuentas ADD COLUMN venta_id text GENERATED ALWAYS AS (datos->>'ventaId') STORED REFERENCES ruizcacao.ventas(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ruizcacao.movimientos_cuenta ADD COLUMN cuenta_id text GENERATED ALWAYS AS (datos->>'cuentaId') STORED REFERENCES ruizcacao.cuentas(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ruizcacao.movimientos_stock ADD COLUMN compra_id text GENERATED ALWAYS AS (datos->>'compraId') STORED REFERENCES ruizcacao.compras(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ruizcacao.movimientos_stock ADD COLUMN venta_id text GENERATED ALWAYS AS (datos->>'ventaId') STORED REFERENCES ruizcacao.ventas(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ruizcacao.movimientos_stock ADD COLUMN conversion_id text GENERATED ALWAYS AS (datos->>'conversionId') STORED REFERENCES ruizcacao.movimientos_stock(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ruizcacao.gastos ADD COLUMN compra_id text GENERATED ALWAYS AS (datos->>'compra_id') STORED REFERENCES ruizcacao.compras(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ruizcacao.gastos ADD COLUMN empleado_id text GENERATED ALWAYS AS (datos->>'empleado_id') STORED REFERENCES ruizcacao.empleados(id) DEFERRABLE INITIALLY DEFERRED;
CREATE UNIQUE INDEX cliente_identificacion ON ruizcacao.clientes((datos->>'identificacion')) WHERE coalesce(datos->>'identificacion','')<>'';
CREATE UNIQUE INDEX proveedor_identificacion ON ruizcacao.proveedores((datos->>'ciRuc')) WHERE coalesce(datos->>'ciRuc','')<>'';
CREATE UNIQUE INDEX empleado_cedula ON ruizcacao.empleados((datos->>'cedula')) WHERE coalesce(datos->>'cedula','')<>'';
CREATE UNIQUE INDEX venta_numero_diario ON ruizcacao.ventas((datos->>'fechaVenta'),((datos->>'numeroFactura')::integer));
CREATE UNIQUE INDEX venta_comprobante ON ruizcacao.ventas(((datos->>'numeroComprobante')::integer));
CREATE UNIQUE INDEX cuenta_compra ON ruizcacao.cuentas(compra_id) WHERE compra_id IS NOT NULL;
CREATE UNIQUE INDEX cuenta_venta ON ruizcacao.cuentas(venta_id) WHERE venta_id IS NOT NULL;
ALTER TABLE ruizcacao.cuentas ADD CONSTRAINT titular_valido CHECK ((datos->>'categoria'='compra' AND proveedor_id IS NOT NULL AND cliente_id IS NULL) OR (datos->>'categoria'='venta' AND cliente_id IS NOT NULL AND proveedor_id IS NULL));
ALTER TABLE ruizcacao.compras ADD CONSTRAINT compra_total_positivo CHECK ((datos->>'totalCompra')::numeric > 0 AND (datos->>'cantidadQq')::numeric > 0);
ALTER TABLE ruizcacao.ventas ADD CONSTRAINT venta_total_positivo CHECK ((datos->>'totalVenta')::numeric > 0 AND (datos->>'pesoBruto')::numeric > 0);
ALTER TABLE ruizcacao.movimientos_cuenta ADD CONSTRAINT movimiento_positivo CHECK ((datos->>'monto')::numeric > 0);

CREATE TABLE ruizcacao.productos(nombre text PRIMARY KEY);
INSERT INTO ruizcacao.productos(nombre) VALUES('Cacao en Baba'),('Cacao Seco'),('Maracuyá');
ALTER TABLE ruizcacao.compras ADD COLUMN producto text GENERATED ALWAYS AS (datos->>'producto') STORED NOT NULL REFERENCES ruizcacao.productos(nombre), ADD COLUMN cantidad_qq numeric(18,2) GENERATED ALWAYS AS ((datos->>'cantidadQq')::numeric) STORED NOT NULL, ADD COLUMN total numeric(18,2) GENERATED ALWAYS AS ((datos->>'totalCompra')::numeric) STORED NOT NULL;
ALTER TABLE ruizcacao.ventas ADD COLUMN producto text GENERATED ALWAYS AS (datos->>'producto') STORED NOT NULL REFERENCES ruizcacao.productos(nombre), ADD COLUMN cantidad_qq numeric(18,2) GENERATED ALWAYS AS ((datos->>'pesoBruto')::numeric) STORED NOT NULL, ADD COLUMN total numeric(18,2) GENERATED ALWAYS AS ((datos->>'totalVenta')::numeric) STORED NOT NULL;
ALTER TABLE ruizcacao.movimientos_stock ADD COLUMN producto text GENERATED ALWAYS AS (datos->>'producto') STORED NOT NULL REFERENCES ruizcacao.productos(nombre);
ALTER TABLE ruizcacao.movimientos_cuenta ADD COLUMN monto numeric(18,2) GENERATED ALWAYS AS ((datos->>'monto')::numeric) STORED NOT NULL;
ALTER TABLE ruizcacao.cuentas ADD COLUMN monto_total numeric(18,2) GENERATED ALWAYS AS ((datos->>'montoTotal')::numeric) STORED NOT NULL, ADD COLUMN monto_aplicado numeric(18,2) GENERATED ALWAYS AS ((datos->>'montoPagado')::numeric) STORED NOT NULL;
ALTER TABLE ruizcacao.gastos ADD COLUMN monto numeric(18,2) GENERATED ALWAYS AS ((datos->>'monto')::numeric) STORED NOT NULL CHECK(monto>0);
CREATE UNIQUE INDEX compra_numero_diario ON ruizcacao.compras((datos->>'fecha'),((datos->>'numeroCompra')::integer));
CREATE VIEW ruizcacao.v_saldos AS SELECT id,datos->>'categoria' AS categoria,cliente_id,proveedor_id,monto_total,monto_aplicado,monto_total-monto_aplicado AS saldo FROM ruizcacao.cuentas WHERE datos->>'estado'<>'anulado';
CREATE VIEW ruizcacao.v_flujo_caja AS SELECT m.id,m.datos->>'fecha' AS fecha,c.datos->>'categoria' AS categoria,CASE WHEN c.datos->>'categoria'='compra' THEN -m.monto ELSE m.monto END AS monto FROM ruizcacao.movimientos_cuenta m JOIN ruizcacao.cuentas c ON c.id=m.cuenta_id WHERE m.datos->>'tipo'='Abono' AND c.datos->>'estado'<>'anulado' UNION ALL SELECT id,datos->>'fecha','gasto_operativo',-monto FROM ruizcacao.gastos WHERE datos->>'tipo'='manual';
