-- Referencia de la migración 2. No ejecutar aisladamente sobre una base vacía.
SET LOCAL TIME ZONE 'America/Guayaquil'; SET CONSTRAINTS ALL IMMEDIATE;
DROP VIEW ruizcacao.v_saldos; DROP VIEW ruizcacao.v_flujo_caja;
ALTER TABLE ruizcacao.clientes ADD COLUMN IF NOT EXISTS nombre_razon_social text;
UPDATE ruizcacao.clientes SET nombre_razon_social=datos->>'nombreRazonSocial';
ALTER TABLE ruizcacao.clientes ALTER COLUMN nombre_razon_social SET NOT NULL;
ALTER TABLE ruizcacao.clientes ADD COLUMN IF NOT EXISTS identificacion text;
UPDATE ruizcacao.clientes SET identificacion=datos->>'identificacion';
ALTER TABLE ruizcacao.clientes ALTER COLUMN identificacion SET NOT NULL;
ALTER TABLE ruizcacao.clientes ADD COLUMN IF NOT EXISTS telefono text;
UPDATE ruizcacao.clientes SET telefono=datos->>'telefono';
ALTER TABLE ruizcacao.clientes ALTER COLUMN telefono SET NOT NULL;
ALTER TABLE ruizcacao.clientes ADD COLUMN IF NOT EXISTS email text;
UPDATE ruizcacao.clientes SET email=NULLIF(datos->>'email','')::text;
ALTER TABLE ruizcacao.clientes ADD COLUMN IF NOT EXISTS direccion text;
UPDATE ruizcacao.clientes SET direccion=NULLIF(datos->>'direccion','')::text;
ALTER TABLE ruizcacao.clientes ADD COLUMN IF NOT EXISTS tipo_cliente text;
UPDATE ruizcacao.clientes SET tipo_cliente=NULLIF(datos->>'tipoCliente','')::text;
ALTER TABLE ruizcacao.clientes ADD COLUMN IF NOT EXISTS notas text;
UPDATE ruizcacao.clientes SET notas=NULLIF(datos->>'notas','')::text;
ALTER TABLE ruizcacao.clientes ADD COLUMN IF NOT EXISTS estado boolean;
UPDATE ruizcacao.clientes SET estado=NULLIF(datos->>'estado','')::boolean;
ALTER TABLE ruizcacao.clientes ALTER COLUMN estado SET NOT NULL;
ALTER TABLE ruizcacao.clientes ADD COLUMN IF NOT EXISTS fecha_registro timestamptz;
UPDATE ruizcacao.clientes SET fecha_registro=NULLIF(datos->>'fechaRegistro','')::timestamptz;
ALTER TABLE ruizcacao.clientes ALTER COLUMN fecha_registro SET NOT NULL;
ALTER TABLE ruizcacao.clientes DROP COLUMN datos CASCADE;
ALTER TABLE ruizcacao.proveedores ADD COLUMN IF NOT EXISTS nombre text;
UPDATE ruizcacao.proveedores SET nombre=datos->>'nombre';
ALTER TABLE ruizcacao.proveedores ALTER COLUMN nombre SET NOT NULL;
ALTER TABLE ruizcacao.proveedores ADD COLUMN IF NOT EXISTS ci_ruc text;
UPDATE ruizcacao.proveedores SET ci_ruc=datos->>'ciRuc';
ALTER TABLE ruizcacao.proveedores ALTER COLUMN ci_ruc SET NOT NULL;
ALTER TABLE ruizcacao.proveedores ADD COLUMN IF NOT EXISTS telefono text;
UPDATE ruizcacao.proveedores SET telefono=NULLIF(datos->>'telefono','')::text;
ALTER TABLE ruizcacao.proveedores ADD COLUMN IF NOT EXISTS correo text;
UPDATE ruizcacao.proveedores SET correo=NULLIF(datos->>'correo','')::text;
ALTER TABLE ruizcacao.proveedores ADD COLUMN IF NOT EXISTS numero_cuenta text;
UPDATE ruizcacao.proveedores SET numero_cuenta=NULLIF(datos->>'numeroCuenta','')::text;
ALTER TABLE ruizcacao.proveedores ADD COLUMN IF NOT EXISTS direccion text;
UPDATE ruizcacao.proveedores SET direccion=NULLIF(datos->>'direccion','')::text;
ALTER TABLE ruizcacao.proveedores ADD COLUMN IF NOT EXISTS estado boolean;
UPDATE ruizcacao.proveedores SET estado=NULLIF(datos->>'estado','')::boolean;
ALTER TABLE ruizcacao.proveedores ALTER COLUMN estado SET NOT NULL;
ALTER TABLE ruizcacao.proveedores ADD COLUMN IF NOT EXISTS fecha_registro timestamptz;
UPDATE ruizcacao.proveedores SET fecha_registro=NULLIF(datos->>'fechaRegistro','')::timestamptz;
ALTER TABLE ruizcacao.proveedores ALTER COLUMN fecha_registro SET NOT NULL;
ALTER TABLE ruizcacao.proveedores DROP COLUMN datos CASCADE;
ALTER TABLE ruizcacao.empleados ADD COLUMN IF NOT EXISTS nombre text;
UPDATE ruizcacao.empleados SET nombre=datos->>'nombre';
ALTER TABLE ruizcacao.empleados ALTER COLUMN nombre SET NOT NULL;
ALTER TABLE ruizcacao.empleados ADD COLUMN IF NOT EXISTS cedula text;
UPDATE ruizcacao.empleados SET cedula=NULLIF(datos->>'cedula','')::text;
ALTER TABLE ruizcacao.empleados ADD COLUMN IF NOT EXISTS telefono text;
UPDATE ruizcacao.empleados SET telefono=NULLIF(datos->>'telefono','')::text;
ALTER TABLE ruizcacao.empleados ADD COLUMN IF NOT EXISTS direccion text;
UPDATE ruizcacao.empleados SET direccion=NULLIF(datos->>'direccion','')::text;
ALTER TABLE ruizcacao.empleados ADD COLUMN IF NOT EXISTS estado boolean;
UPDATE ruizcacao.empleados SET estado=NULLIF(datos->>'estado','')::boolean;
ALTER TABLE ruizcacao.empleados ALTER COLUMN estado SET NOT NULL;
ALTER TABLE ruizcacao.empleados ADD COLUMN IF NOT EXISTS fecha_registro timestamptz;
UPDATE ruizcacao.empleados SET fecha_registro=NULLIF(datos->>'fechaRegistro','')::timestamptz;
ALTER TABLE ruizcacao.empleados ALTER COLUMN fecha_registro SET NOT NULL;
ALTER TABLE ruizcacao.empleados DROP COLUMN datos CASCADE;
ALTER TABLE ruizcacao.compras ALTER COLUMN proveedor_id DROP EXPRESSION;
ALTER TABLE ruizcacao.compras ALTER COLUMN producto DROP EXPRESSION;
ALTER TABLE ruizcacao.compras ALTER COLUMN cantidad_qq DROP EXPRESSION;
ALTER TABLE ruizcacao.compras ALTER COLUMN total DROP EXPRESSION;
ALTER TABLE ruizcacao.compras ADD COLUMN IF NOT EXISTS numero_compra integer;
UPDATE ruizcacao.compras SET numero_compra=NULLIF(datos->>'numeroCompra','')::integer;
ALTER TABLE ruizcacao.compras ALTER COLUMN numero_compra SET NOT NULL;
ALTER TABLE ruizcacao.compras ADD COLUMN IF NOT EXISTS fecha date;
UPDATE ruizcacao.compras SET fecha=NULLIF(datos->>'fecha','')::date;
ALTER TABLE ruizcacao.compras ALTER COLUMN fecha SET NOT NULL;
ALTER TABLE ruizcacao.compras ADD COLUMN IF NOT EXISTS fecha_hora_registro timestamptz;
UPDATE ruizcacao.compras SET fecha_hora_registro=NULLIF(datos->>'fechaHoraRegistro','')::timestamptz;
ALTER TABLE ruizcacao.compras ALTER COLUMN fecha_hora_registro SET NOT NULL;
ALTER TABLE ruizcacao.compras ADD COLUMN IF NOT EXISTS proveedor_id text;
UPDATE ruizcacao.compras SET proveedor_id=datos->>'proveedorId';
ALTER TABLE ruizcacao.compras ALTER COLUMN proveedor_id SET NOT NULL;
ALTER TABLE ruizcacao.compras ADD COLUMN IF NOT EXISTS proveedor_nombre text;
UPDATE ruizcacao.compras SET proveedor_nombre=datos->>'proveedorNombre';
ALTER TABLE ruizcacao.compras ALTER COLUMN proveedor_nombre SET NOT NULL;
ALTER TABLE ruizcacao.compras ADD COLUMN IF NOT EXISTS producto text;
UPDATE ruizcacao.compras SET producto=datos->>'producto';
ALTER TABLE ruizcacao.compras ALTER COLUMN producto SET NOT NULL;
ALTER TABLE ruizcacao.compras ADD COLUMN IF NOT EXISTS cantidad_qq numeric(18,2);
UPDATE ruizcacao.compras SET cantidad_qq=NULLIF(datos->>'cantidadQq','')::numeric(18,2);
ALTER TABLE ruizcacao.compras ALTER COLUMN cantidad_qq SET NOT NULL;
ALTER TABLE ruizcacao.compras ADD COLUMN IF NOT EXISTS precio_compra_qq numeric(18,2);
UPDATE ruizcacao.compras SET precio_compra_qq=NULLIF(datos->>'precioCompraQq','')::numeric(18,2);
ALTER TABLE ruizcacao.compras ALTER COLUMN precio_compra_qq SET NOT NULL;
ALTER TABLE ruizcacao.compras ADD COLUMN IF NOT EXISTS impuesto_porcentaje numeric(18,2);
UPDATE ruizcacao.compras SET impuesto_porcentaje=NULLIF(datos->>'impuestoPorcentaje','')::numeric(18,2);
ALTER TABLE ruizcacao.compras ALTER COLUMN impuesto_porcentaje SET NOT NULL;
ALTER TABLE ruizcacao.compras ADD COLUMN IF NOT EXISTS subtotal numeric(18,2);
UPDATE ruizcacao.compras SET subtotal=NULLIF(datos->>'subtotal','')::numeric(18,2);
ALTER TABLE ruizcacao.compras ALTER COLUMN subtotal SET NOT NULL;
ALTER TABLE ruizcacao.compras ADD COLUMN IF NOT EXISTS monto_impuesto numeric(18,2);
UPDATE ruizcacao.compras SET monto_impuesto=NULLIF(datos->>'montoImpuesto','')::numeric(18,2);
ALTER TABLE ruizcacao.compras ALTER COLUMN monto_impuesto SET NOT NULL;
ALTER TABLE ruizcacao.compras ADD COLUMN IF NOT EXISTS total numeric(18,2);
UPDATE ruizcacao.compras SET total=NULLIF(datos->>'totalCompra','')::numeric(18,2);
ALTER TABLE ruizcacao.compras ALTER COLUMN total SET NOT NULL;
ALTER TABLE ruizcacao.compras ADD COLUMN IF NOT EXISTS monto_pagado_inicial numeric(18,2);
UPDATE ruizcacao.compras SET monto_pagado_inicial=NULLIF(datos->>'montoPagadoInicial','')::numeric(18,2);
ALTER TABLE ruizcacao.compras ALTER COLUMN monto_pagado_inicial SET NOT NULL;
ALTER TABLE ruizcacao.compras ADD COLUMN IF NOT EXISTS metodo_pago text;
UPDATE ruizcacao.compras SET metodo_pago=datos->>'metodoPago';
ALTER TABLE ruizcacao.compras ALTER COLUMN metodo_pago SET NOT NULL;
ALTER TABLE ruizcacao.compras ADD COLUMN IF NOT EXISTS monto_efectivo numeric(18,2);
UPDATE ruizcacao.compras SET monto_efectivo=NULLIF(datos->>'montoEfectivo','')::numeric(18,2);
ALTER TABLE ruizcacao.compras ADD COLUMN IF NOT EXISTS monto_transferencia numeric(18,2);
UPDATE ruizcacao.compras SET monto_transferencia=NULLIF(datos->>'montoTransferencia','')::numeric(18,2);
ALTER TABLE ruizcacao.compras ADD COLUMN IF NOT EXISTS comprobante text;
UPDATE ruizcacao.compras SET comprobante=NULLIF(datos->>'comprobante','')::text;
ALTER TABLE ruizcacao.compras ADD COLUMN IF NOT EXISTS observacion text;
UPDATE ruizcacao.compras SET observacion=NULLIF(datos->>'observacion','')::text;
ALTER TABLE ruizcacao.compras DROP COLUMN datos CASCADE;
ALTER TABLE ruizcacao.ventas ALTER COLUMN cliente_id DROP EXPRESSION;
ALTER TABLE ruizcacao.ventas ALTER COLUMN producto DROP EXPRESSION;
ALTER TABLE ruizcacao.ventas ALTER COLUMN cantidad_qq DROP EXPRESSION;
ALTER TABLE ruizcacao.ventas ALTER COLUMN total DROP EXPRESSION;
ALTER TABLE ruizcacao.ventas ADD COLUMN IF NOT EXISTS numero_factura integer;
UPDATE ruizcacao.ventas SET numero_factura=NULLIF(datos->>'numeroFactura','')::integer;
ALTER TABLE ruizcacao.ventas ALTER COLUMN numero_factura SET NOT NULL;
ALTER TABLE ruizcacao.ventas ADD COLUMN IF NOT EXISTS numero_comprobante integer;
UPDATE ruizcacao.ventas SET numero_comprobante=NULLIF(datos->>'numeroComprobante','')::integer;
ALTER TABLE ruizcacao.ventas ALTER COLUMN numero_comprobante SET NOT NULL;
ALTER TABLE ruizcacao.ventas ADD COLUMN IF NOT EXISTS subtotal numeric(18,2);
UPDATE ruizcacao.ventas SET subtotal=NULLIF(datos->>'subtotal','')::numeric(18,2);
ALTER TABLE ruizcacao.ventas ALTER COLUMN subtotal SET NOT NULL;
ALTER TABLE ruizcacao.ventas ADD COLUMN IF NOT EXISTS monto_impuesto numeric(18,2);
UPDATE ruizcacao.ventas SET monto_impuesto=NULLIF(datos->>'montoImpuesto','')::numeric(18,2);
ALTER TABLE ruizcacao.ventas ALTER COLUMN monto_impuesto SET NOT NULL;
ALTER TABLE ruizcacao.ventas ADD COLUMN IF NOT EXISTS total numeric(18,2);
UPDATE ruizcacao.ventas SET total=NULLIF(datos->>'totalVenta','')::numeric(18,2);
ALTER TABLE ruizcacao.ventas ALTER COLUMN total SET NOT NULL;
ALTER TABLE ruizcacao.ventas ADD COLUMN IF NOT EXISTS saldo_pendiente numeric(18,2);
UPDATE ruizcacao.ventas SET saldo_pendiente=NULLIF(datos->>'saldoPendiente','')::numeric(18,2);
ALTER TABLE ruizcacao.ventas ALTER COLUMN saldo_pendiente SET NOT NULL;
ALTER TABLE ruizcacao.ventas ADD COLUMN IF NOT EXISTS estado_cobro text;
UPDATE ruizcacao.ventas SET estado_cobro=datos->>'estadoCobro';
ALTER TABLE ruizcacao.ventas ALTER COLUMN estado_cobro SET NOT NULL;
ALTER TABLE ruizcacao.ventas ADD COLUMN IF NOT EXISTS fecha_venta date;
UPDATE ruizcacao.ventas SET fecha_venta=NULLIF(datos->>'fechaVenta','')::date;
ALTER TABLE ruizcacao.ventas ALTER COLUMN fecha_venta SET NOT NULL;
ALTER TABLE ruizcacao.ventas ADD COLUMN IF NOT EXISTS fecha_hora_registro timestamptz;
UPDATE ruizcacao.ventas SET fecha_hora_registro=NULLIF(datos->>'fechaHoraRegistro','')::timestamptz;
ALTER TABLE ruizcacao.ventas ALTER COLUMN fecha_hora_registro SET NOT NULL;
ALTER TABLE ruizcacao.ventas ADD COLUMN IF NOT EXISTS cliente_id text;
UPDATE ruizcacao.ventas SET cliente_id=datos->>'clienteId';
ALTER TABLE ruizcacao.ventas ALTER COLUMN cliente_id SET NOT NULL;
ALTER TABLE ruizcacao.ventas ADD COLUMN IF NOT EXISTS producto text;
UPDATE ruizcacao.ventas SET producto=datos->>'producto';
ALTER TABLE ruizcacao.ventas ALTER COLUMN producto SET NOT NULL;
ALTER TABLE ruizcacao.ventas ADD COLUMN IF NOT EXISTS cantidad_qq numeric(18,2);
UPDATE ruizcacao.ventas SET cantidad_qq=NULLIF(datos->>'pesoBruto','')::numeric(18,2);
ALTER TABLE ruizcacao.ventas ALTER COLUMN cantidad_qq SET NOT NULL;
ALTER TABLE ruizcacao.ventas ADD COLUMN IF NOT EXISTS precio_unitario numeric(18,2);
UPDATE ruizcacao.ventas SET precio_unitario=NULLIF(datos->>'precioUnitario','')::numeric(18,2);
ALTER TABLE ruizcacao.ventas ALTER COLUMN precio_unitario SET NOT NULL;
ALTER TABLE ruizcacao.ventas ADD COLUMN IF NOT EXISTS impuesto_porcentaje numeric(18,2);
UPDATE ruizcacao.ventas SET impuesto_porcentaje=NULLIF(datos->>'impuestoPorcentaje','')::numeric(18,2);
ALTER TABLE ruizcacao.ventas ALTER COLUMN impuesto_porcentaje SET NOT NULL;
ALTER TABLE ruizcacao.ventas ADD COLUMN IF NOT EXISTS metodo_pago text;
UPDATE ruizcacao.ventas SET metodo_pago=datos->>'metodoPago';
ALTER TABLE ruizcacao.ventas ALTER COLUMN metodo_pago SET NOT NULL;
ALTER TABLE ruizcacao.ventas ADD COLUMN IF NOT EXISTS monto_efectivo numeric(18,2);
UPDATE ruizcacao.ventas SET monto_efectivo=NULLIF(datos->>'montoEfectivo','')::numeric(18,2);
ALTER TABLE ruizcacao.ventas ADD COLUMN IF NOT EXISTS monto_transferencia numeric(18,2);
UPDATE ruizcacao.ventas SET monto_transferencia=NULLIF(datos->>'montoTransferencia','')::numeric(18,2);
ALTER TABLE ruizcacao.ventas ADD COLUMN IF NOT EXISTS monto_recibido numeric(18,2);
UPDATE ruizcacao.ventas SET monto_recibido=NULLIF(datos->>'montoRecibido','')::numeric(18,2);
ALTER TABLE ruizcacao.ventas ALTER COLUMN monto_recibido SET NOT NULL;
ALTER TABLE ruizcacao.ventas ADD COLUMN IF NOT EXISTS numero_lote text;
UPDATE ruizcacao.ventas SET numero_lote=NULLIF(datos->>'numeroLote','')::text;
ALTER TABLE ruizcacao.ventas ADD COLUMN IF NOT EXISTS observaciones text;
UPDATE ruizcacao.ventas SET observaciones=NULLIF(datos->>'observaciones','')::text;
ALTER TABLE ruizcacao.ventas DROP COLUMN datos CASCADE;
ALTER TABLE ruizcacao.cuentas ALTER COLUMN cliente_id DROP EXPRESSION;
ALTER TABLE ruizcacao.cuentas ALTER COLUMN proveedor_id DROP EXPRESSION;
ALTER TABLE ruizcacao.cuentas ALTER COLUMN compra_id DROP EXPRESSION;
ALTER TABLE ruizcacao.cuentas ALTER COLUMN venta_id DROP EXPRESSION;
ALTER TABLE ruizcacao.cuentas ALTER COLUMN monto_total DROP EXPRESSION;
ALTER TABLE ruizcacao.cuentas ALTER COLUMN monto_aplicado DROP EXPRESSION;
ALTER TABLE ruizcacao.cuentas ADD COLUMN IF NOT EXISTS origen text;
UPDATE ruizcacao.cuentas SET origen=datos->>'origen';
ALTER TABLE ruizcacao.cuentas ALTER COLUMN origen SET NOT NULL;
ALTER TABLE ruizcacao.cuentas ADD COLUMN IF NOT EXISTS categoria text;
UPDATE ruizcacao.cuentas SET categoria=datos->>'categoria';
ALTER TABLE ruizcacao.cuentas ALTER COLUMN categoria SET NOT NULL;
ALTER TABLE ruizcacao.cuentas ADD COLUMN IF NOT EXISTS compra_id text;
UPDATE ruizcacao.cuentas SET compra_id=NULLIF(datos->>'compraId','')::text;
ALTER TABLE ruizcacao.cuentas ADD COLUMN IF NOT EXISTS numero_compra integer;
UPDATE ruizcacao.cuentas SET numero_compra=NULLIF(datos->>'numeroCompra','')::integer;
ALTER TABLE ruizcacao.cuentas ADD COLUMN IF NOT EXISTS proveedor_id text;
UPDATE ruizcacao.cuentas SET proveedor_id=NULLIF(datos->>'proveedorId','')::text;
ALTER TABLE ruizcacao.cuentas ADD COLUMN IF NOT EXISTS proveedor_nombre text;
UPDATE ruizcacao.cuentas SET proveedor_nombre=NULLIF(datos->>'proveedorNombre','')::text;
ALTER TABLE ruizcacao.cuentas ADD COLUMN IF NOT EXISTS venta_id text;
UPDATE ruizcacao.cuentas SET venta_id=NULLIF(datos->>'ventaId','')::text;
ALTER TABLE ruizcacao.cuentas ADD COLUMN IF NOT EXISTS numero_factura integer;
UPDATE ruizcacao.cuentas SET numero_factura=NULLIF(datos->>'numeroFactura','')::integer;
ALTER TABLE ruizcacao.cuentas ADD COLUMN IF NOT EXISTS cliente_id text;
UPDATE ruizcacao.cuentas SET cliente_id=NULLIF(datos->>'clienteId','')::text;
ALTER TABLE ruizcacao.cuentas ADD COLUMN IF NOT EXISTS monto_total numeric(18,2);
UPDATE ruizcacao.cuentas SET monto_total=NULLIF(datos->>'montoTotal','')::numeric(18,2);
ALTER TABLE ruizcacao.cuentas ALTER COLUMN monto_total SET NOT NULL;
ALTER TABLE ruizcacao.cuentas ADD COLUMN IF NOT EXISTS monto_aplicado numeric(18,2);
UPDATE ruizcacao.cuentas SET monto_aplicado=NULLIF(datos->>'montoPagado','')::numeric(18,2);
ALTER TABLE ruizcacao.cuentas ALTER COLUMN monto_aplicado SET NOT NULL;
ALTER TABLE ruizcacao.cuentas ADD COLUMN IF NOT EXISTS fecha date;
UPDATE ruizcacao.cuentas SET fecha=NULLIF(datos->>'fecha','')::date;
ALTER TABLE ruizcacao.cuentas ALTER COLUMN fecha SET NOT NULL;
ALTER TABLE ruizcacao.cuentas ADD COLUMN IF NOT EXISTS fecha_hora_registro timestamptz;
UPDATE ruizcacao.cuentas SET fecha_hora_registro=NULLIF(datos->>'fechaHoraRegistro','')::timestamptz;
ALTER TABLE ruizcacao.cuentas ALTER COLUMN fecha_hora_registro SET NOT NULL;
ALTER TABLE ruizcacao.cuentas ADD COLUMN IF NOT EXISTS fecha_ultimo_movimiento timestamptz;
UPDATE ruizcacao.cuentas SET fecha_ultimo_movimiento=NULLIF(datos->>'fechaUltimoMovimiento','')::timestamptz;
ALTER TABLE ruizcacao.cuentas ALTER COLUMN fecha_ultimo_movimiento SET NOT NULL;
ALTER TABLE ruizcacao.cuentas ADD COLUMN IF NOT EXISTS estado text;
UPDATE ruizcacao.cuentas SET estado=datos->>'estado';
ALTER TABLE ruizcacao.cuentas ALTER COLUMN estado SET NOT NULL;
ALTER TABLE ruizcacao.cuentas ADD COLUMN IF NOT EXISTS observacion text;
UPDATE ruizcacao.cuentas SET observacion=NULLIF(datos->>'observacion','')::text;
ALTER TABLE ruizcacao.cuentas ADD COLUMN IF NOT EXISTS comprobante text;
UPDATE ruizcacao.cuentas SET comprobante=NULLIF(datos->>'comprobante','')::text;
ALTER TABLE ruizcacao.cuentas ADD COLUMN IF NOT EXISTS motivo_anulacion text;
UPDATE ruizcacao.cuentas SET motivo_anulacion=NULLIF(datos->>'motivoAnulacion','')::text;
ALTER TABLE ruizcacao.cuentas DROP COLUMN datos CASCADE;
ALTER TABLE ruizcacao.movimientos_cuenta ALTER COLUMN cuenta_id DROP EXPRESSION;
ALTER TABLE ruizcacao.movimientos_cuenta ALTER COLUMN monto DROP EXPRESSION;
ALTER TABLE ruizcacao.movimientos_cuenta ADD COLUMN IF NOT EXISTS cuenta_id text;
UPDATE ruizcacao.movimientos_cuenta SET cuenta_id=datos->>'cuentaId';
ALTER TABLE ruizcacao.movimientos_cuenta ALTER COLUMN cuenta_id SET NOT NULL;
ALTER TABLE ruizcacao.movimientos_cuenta ADD COLUMN IF NOT EXISTS categoria text;
UPDATE ruizcacao.movimientos_cuenta SET categoria=datos->>'categoria';
ALTER TABLE ruizcacao.movimientos_cuenta ALTER COLUMN categoria SET NOT NULL;
ALTER TABLE ruizcacao.movimientos_cuenta ADD COLUMN IF NOT EXISTS proveedor_id text;
UPDATE ruizcacao.movimientos_cuenta SET proveedor_id=NULLIF(datos->>'proveedorId','')::text;
ALTER TABLE ruizcacao.movimientos_cuenta ADD COLUMN IF NOT EXISTS cliente_id text;
UPDATE ruizcacao.movimientos_cuenta SET cliente_id=NULLIF(datos->>'clienteId','')::text;
ALTER TABLE ruizcacao.movimientos_cuenta ADD COLUMN IF NOT EXISTS fecha date;
UPDATE ruizcacao.movimientos_cuenta SET fecha=NULLIF(datos->>'fecha','')::date;
ALTER TABLE ruizcacao.movimientos_cuenta ALTER COLUMN fecha SET NOT NULL;
ALTER TABLE ruizcacao.movimientos_cuenta ADD COLUMN IF NOT EXISTS fecha_hora_registro timestamptz;
UPDATE ruizcacao.movimientos_cuenta SET fecha_hora_registro=NULLIF(datos->>'fechaHoraRegistro','')::timestamptz;
ALTER TABLE ruizcacao.movimientos_cuenta ALTER COLUMN fecha_hora_registro SET NOT NULL;
ALTER TABLE ruizcacao.movimientos_cuenta ADD COLUMN IF NOT EXISTS tipo text;
UPDATE ruizcacao.movimientos_cuenta SET tipo=datos->>'tipo';
ALTER TABLE ruizcacao.movimientos_cuenta ALTER COLUMN tipo SET NOT NULL;
ALTER TABLE ruizcacao.movimientos_cuenta ADD COLUMN IF NOT EXISTS monto numeric(18,2);
UPDATE ruizcacao.movimientos_cuenta SET monto=NULLIF(datos->>'monto','')::numeric(18,2);
ALTER TABLE ruizcacao.movimientos_cuenta ALTER COLUMN monto SET NOT NULL;
ALTER TABLE ruizcacao.movimientos_cuenta ADD COLUMN IF NOT EXISTS metodo_pago text;
UPDATE ruizcacao.movimientos_cuenta SET metodo_pago=datos->>'metodoPago';
ALTER TABLE ruizcacao.movimientos_cuenta ALTER COLUMN metodo_pago SET NOT NULL;
ALTER TABLE ruizcacao.movimientos_cuenta ADD COLUMN IF NOT EXISTS monto_efectivo numeric(18,2);
UPDATE ruizcacao.movimientos_cuenta SET monto_efectivo=NULLIF(datos->>'montoEfectivo','')::numeric(18,2);
ALTER TABLE ruizcacao.movimientos_cuenta ADD COLUMN IF NOT EXISTS monto_transferencia numeric(18,2);
UPDATE ruizcacao.movimientos_cuenta SET monto_transferencia=NULLIF(datos->>'montoTransferencia','')::numeric(18,2);
ALTER TABLE ruizcacao.movimientos_cuenta ADD COLUMN IF NOT EXISTS observacion text;
UPDATE ruizcacao.movimientos_cuenta SET observacion=datos->>'observacion';
ALTER TABLE ruizcacao.movimientos_cuenta ALTER COLUMN observacion SET NOT NULL;
ALTER TABLE ruizcacao.movimientos_cuenta ADD COLUMN IF NOT EXISTS numero_comprobante text;
UPDATE ruizcacao.movimientos_cuenta SET numero_comprobante=NULLIF(datos->>'numeroComprobante','')::text;
ALTER TABLE ruizcacao.movimientos_cuenta ADD COLUMN IF NOT EXISTS comprobante text;
UPDATE ruizcacao.movimientos_cuenta SET comprobante=NULLIF(datos->>'comprobante','')::text;
ALTER TABLE ruizcacao.movimientos_cuenta DROP COLUMN datos CASCADE;
ALTER TABLE ruizcacao.movimientos_stock ALTER COLUMN compra_id DROP EXPRESSION;
ALTER TABLE ruizcacao.movimientos_stock ALTER COLUMN venta_id DROP EXPRESSION;
ALTER TABLE ruizcacao.movimientos_stock ALTER COLUMN conversion_id DROP EXPRESSION;
ALTER TABLE ruizcacao.movimientos_stock ALTER COLUMN producto DROP EXPRESSION;
ALTER TABLE ruizcacao.movimientos_stock ADD COLUMN IF NOT EXISTS fecha date;
UPDATE ruizcacao.movimientos_stock SET fecha=NULLIF(datos->>'fecha','')::date;
ALTER TABLE ruizcacao.movimientos_stock ALTER COLUMN fecha SET NOT NULL;
ALTER TABLE ruizcacao.movimientos_stock ADD COLUMN IF NOT EXISTS fecha_hora_registro timestamptz;
UPDATE ruizcacao.movimientos_stock SET fecha_hora_registro=NULLIF(datos->>'fechaHoraRegistro','')::timestamptz;
ALTER TABLE ruizcacao.movimientos_stock ALTER COLUMN fecha_hora_registro SET NOT NULL;
ALTER TABLE ruizcacao.movimientos_stock ADD COLUMN IF NOT EXISTS tipo text;
UPDATE ruizcacao.movimientos_stock SET tipo=datos->>'tipo';
ALTER TABLE ruizcacao.movimientos_stock ALTER COLUMN tipo SET NOT NULL;
ALTER TABLE ruizcacao.movimientos_stock ADD COLUMN IF NOT EXISTS producto text;
UPDATE ruizcacao.movimientos_stock SET producto=datos->>'producto';
ALTER TABLE ruizcacao.movimientos_stock ALTER COLUMN producto SET NOT NULL;
ALTER TABLE ruizcacao.movimientos_stock ADD COLUMN IF NOT EXISTS entrada_qq numeric(18,2);
UPDATE ruizcacao.movimientos_stock SET entrada_qq=NULLIF(datos->>'entradaQq','')::numeric(18,2);
ALTER TABLE ruizcacao.movimientos_stock ALTER COLUMN entrada_qq SET NOT NULL;
ALTER TABLE ruizcacao.movimientos_stock ADD COLUMN IF NOT EXISTS salida_qq numeric(18,2);
UPDATE ruizcacao.movimientos_stock SET salida_qq=NULLIF(datos->>'salidaQq','')::numeric(18,2);
ALTER TABLE ruizcacao.movimientos_stock ALTER COLUMN salida_qq SET NOT NULL;
ALTER TABLE ruizcacao.movimientos_stock ADD COLUMN IF NOT EXISTS stock_resultante numeric(18,2);
UPDATE ruizcacao.movimientos_stock SET stock_resultante=NULLIF(datos->>'stockResultante','')::numeric(18,2);
ALTER TABLE ruizcacao.movimientos_stock ALTER COLUMN stock_resultante SET NOT NULL;
ALTER TABLE ruizcacao.movimientos_stock ADD COLUMN IF NOT EXISTS detalle text;
UPDATE ruizcacao.movimientos_stock SET detalle=datos->>'detalle';
ALTER TABLE ruizcacao.movimientos_stock ALTER COLUMN detalle SET NOT NULL;
ALTER TABLE ruizcacao.movimientos_stock ADD COLUMN IF NOT EXISTS gasto_generado_id text;
UPDATE ruizcacao.movimientos_stock SET gasto_generado_id=NULLIF(datos->>'gastoGeneradoId','')::text;
ALTER TABLE ruizcacao.movimientos_stock ADD COLUMN IF NOT EXISTS venta_id text;
UPDATE ruizcacao.movimientos_stock SET venta_id=NULLIF(datos->>'ventaId','')::text;
ALTER TABLE ruizcacao.movimientos_stock ADD COLUMN IF NOT EXISTS compra_id text;
UPDATE ruizcacao.movimientos_stock SET compra_id=NULLIF(datos->>'compraId','')::text;
ALTER TABLE ruizcacao.movimientos_stock ADD COLUMN IF NOT EXISTS conversion_id text;
UPDATE ruizcacao.movimientos_stock SET conversion_id=NULLIF(datos->>'conversionId','')::text;
ALTER TABLE ruizcacao.movimientos_stock ADD COLUMN IF NOT EXISTS proveedor_id text;
UPDATE ruizcacao.movimientos_stock SET proveedor_id=NULLIF(datos->>'proveedorId','')::text;
ALTER TABLE ruizcacao.movimientos_stock ADD COLUMN IF NOT EXISTS proveedor_nombre text;
UPDATE ruizcacao.movimientos_stock SET proveedor_nombre=NULLIF(datos->>'proveedorNombre','')::text;
ALTER TABLE ruizcacao.movimientos_stock ADD COLUMN IF NOT EXISTS factor_conversion numeric(18,6);
UPDATE ruizcacao.movimientos_stock SET factor_conversion=NULLIF(datos->>'factorConversion','')::numeric(18,6);
ALTER TABLE ruizcacao.movimientos_stock ADD COLUMN IF NOT EXISTS cantidad_obtenida_qq numeric(18,2);
UPDATE ruizcacao.movimientos_stock SET cantidad_obtenida_qq=NULLIF(datos->>'cantidadObtenidaQq','')::numeric(18,2);
ALTER TABLE ruizcacao.movimientos_stock ADD COLUMN IF NOT EXISTS diferencia_qq numeric(18,2);
UPDATE ruizcacao.movimientos_stock SET diferencia_qq=NULLIF(datos->>'diferenciaQq','')::numeric(18,2);
ALTER TABLE ruizcacao.movimientos_stock ADD COLUMN IF NOT EXISTS estado_pago text;
UPDATE ruizcacao.movimientos_stock SET estado_pago=NULLIF(datos->>'estadoPago','')::text;
ALTER TABLE ruizcacao.movimientos_stock ADD COLUMN IF NOT EXISTS monto_abono numeric(18,2);
UPDATE ruizcacao.movimientos_stock SET monto_abono=NULLIF(datos->>'montoAbono','')::numeric(18,2);
ALTER TABLE ruizcacao.movimientos_stock ADD COLUMN IF NOT EXISTS monto_total numeric(18,2);
UPDATE ruizcacao.movimientos_stock SET monto_total=NULLIF(datos->>'montoTotal','')::numeric(18,2);
ALTER TABLE ruizcacao.movimientos_stock ADD COLUMN IF NOT EXISTS saldo_pendiente numeric(18,2);
UPDATE ruizcacao.movimientos_stock SET saldo_pendiente=NULLIF(datos->>'saldoPendiente','')::numeric(18,2);
ALTER TABLE ruizcacao.movimientos_stock ADD COLUMN IF NOT EXISTS comprobante text;
UPDATE ruizcacao.movimientos_stock SET comprobante=NULLIF(datos->>'comprobante','')::text;
ALTER TABLE ruizcacao.movimientos_stock ADD COLUMN IF NOT EXISTS observacion text;
UPDATE ruizcacao.movimientos_stock SET observacion=NULLIF(datos->>'observacion','')::text;
ALTER TABLE ruizcacao.movimientos_stock DROP COLUMN datos CASCADE;
ALTER TABLE ruizcacao.gastos ALTER COLUMN compra_id DROP EXPRESSION;
ALTER TABLE ruizcacao.gastos ALTER COLUMN empleado_id DROP EXPRESSION;
ALTER TABLE ruizcacao.gastos ALTER COLUMN monto DROP EXPRESSION;
ALTER TABLE ruizcacao.gastos ADD COLUMN IF NOT EXISTS fecha date;
UPDATE ruizcacao.gastos SET fecha=NULLIF(datos->>'fecha','')::date;
ALTER TABLE ruizcacao.gastos ALTER COLUMN fecha SET NOT NULL;
ALTER TABLE ruizcacao.gastos ADD COLUMN IF NOT EXISTS fecha_hora_registro timestamptz;
UPDATE ruizcacao.gastos SET fecha_hora_registro=NULLIF(datos->>'fechaHoraRegistro','')::timestamptz;
ALTER TABLE ruizcacao.gastos ALTER COLUMN fecha_hora_registro SET NOT NULL;
ALTER TABLE ruizcacao.gastos ADD COLUMN IF NOT EXISTS categoria text;
UPDATE ruizcacao.gastos SET categoria=datos->>'categoria';
ALTER TABLE ruizcacao.gastos ALTER COLUMN categoria SET NOT NULL;
ALTER TABLE ruizcacao.gastos ADD COLUMN IF NOT EXISTS concepto text;
UPDATE ruizcacao.gastos SET concepto=datos->>'concepto';
ALTER TABLE ruizcacao.gastos ALTER COLUMN concepto SET NOT NULL;
ALTER TABLE ruizcacao.gastos ADD COLUMN IF NOT EXISTS monto numeric(18,2);
UPDATE ruizcacao.gastos SET monto=NULLIF(datos->>'monto','')::numeric(18,2);
ALTER TABLE ruizcacao.gastos ALTER COLUMN monto SET NOT NULL;
ALTER TABLE ruizcacao.gastos ADD COLUMN IF NOT EXISTS comprobante text;
UPDATE ruizcacao.gastos SET comprobante=NULLIF(datos->>'comprobante','')::text;
ALTER TABLE ruizcacao.gastos ADD COLUMN IF NOT EXISTS observacion text;
UPDATE ruizcacao.gastos SET observacion=datos->>'observacion';
ALTER TABLE ruizcacao.gastos ALTER COLUMN observacion SET NOT NULL;
ALTER TABLE ruizcacao.gastos ADD COLUMN IF NOT EXISTS tipo text;
UPDATE ruizcacao.gastos SET tipo=datos->>'tipo';
ALTER TABLE ruizcacao.gastos ALTER COLUMN tipo SET NOT NULL;
ALTER TABLE ruizcacao.gastos ADD COLUMN IF NOT EXISTS referencia_stock_id text;
UPDATE ruizcacao.gastos SET referencia_stock_id=NULLIF(datos->>'referenciaStockId','')::text;
ALTER TABLE ruizcacao.gastos ADD COLUMN IF NOT EXISTS compra_id text;
UPDATE ruizcacao.gastos SET compra_id=NULLIF(datos->>'compra_id','')::text;
ALTER TABLE ruizcacao.gastos ADD COLUMN IF NOT EXISTS empleado_id text;
UPDATE ruizcacao.gastos SET empleado_id=NULLIF(datos->>'empleado_id','')::text;
ALTER TABLE ruizcacao.gastos ADD COLUMN IF NOT EXISTS tipo_pago text;
UPDATE ruizcacao.gastos SET tipo_pago=NULLIF(datos->>'tipo_pago','')::text;
ALTER TABLE ruizcacao.gastos ADD COLUMN IF NOT EXISTS empleado_nombre text;
UPDATE ruizcacao.gastos SET empleado_nombre=NULLIF(datos->>'empleado_nombre','')::text;
ALTER TABLE ruizcacao.gastos ADD COLUMN IF NOT EXISTS proveedor_id text;
UPDATE ruizcacao.gastos SET proveedor_id=NULLIF(datos->>'proveedor_id','')::text;
ALTER TABLE ruizcacao.gastos ADD COLUMN IF NOT EXISTS proveedor_nombre text;
UPDATE ruizcacao.gastos SET proveedor_nombre=NULLIF(datos->>'proveedor_nombre','')::text;
ALTER TABLE ruizcacao.gastos ADD COLUMN IF NOT EXISTS estado_pago_proveedor text;
UPDATE ruizcacao.gastos SET estado_pago_proveedor=NULLIF(datos->>'estado_pago_proveedor','')::text;
ALTER TABLE ruizcacao.gastos ADD COLUMN IF NOT EXISTS monto_abono numeric(18,2);
UPDATE ruizcacao.gastos SET monto_abono=NULLIF(datos->>'monto_abono','')::numeric(18,2);
ALTER TABLE ruizcacao.gastos ADD COLUMN IF NOT EXISTS saldo_pendiente_proveedor numeric(18,2);
UPDATE ruizcacao.gastos SET saldo_pendiente_proveedor=NULLIF(datos->>'saldo_pendiente_proveedor','')::numeric(18,2);
ALTER TABLE ruizcacao.gastos DROP COLUMN datos CASCADE;

CREATE TABLE ruizcacao.existencias(producto text PRIMARY KEY REFERENCES ruizcacao.productos(nombre), cantidad_qq numeric(18,2) NOT NULL CHECK(cantidad_qq>=0), costo_unitario_promedio numeric(18,6) NOT NULL CHECK(costo_unitario_promedio>=0));
INSERT INTO ruizcacao.existencias SELECT p.nombre, coalesce((c.datos->'stock'->>p.nombre)::numeric,0), coalesce((c.datos->'costoUnitarioPromedio'->>p.nombre)::numeric,0) FROM ruizcacao.productos p LEFT JOIN ruizcacao.configuracion c ON c.id=1;
ALTER TABLE ruizcacao.configuracion ADD COLUMN ultimo_factor_usado numeric(8,3) NOT NULL DEFAULT 3.5 CHECK(ultimo_factor_usado BETWEEN 2.8 AND 5.3);
UPDATE ruizcacao.configuracion SET ultimo_factor_usado=coalesce((datos->>'ultimoFactorUsado')::numeric,3.5);
ALTER TABLE ruizcacao.configuracion DROP COLUMN datos;
INSERT INTO ruizcacao.configuracion(id) VALUES(1) ON CONFLICT DO NOTHING;
CREATE UNIQUE INDEX cliente_identificacion ON ruizcacao.clientes(identificacion) WHERE identificacion<>'';
CREATE UNIQUE INDEX proveedor_identificacion ON ruizcacao.proveedores(ci_ruc) WHERE ci_ruc<>'';
CREATE UNIQUE INDEX empleado_cedula ON ruizcacao.empleados(cedula) WHERE cedula<>'';
CREATE UNIQUE INDEX compra_numero_diario ON ruizcacao.compras(fecha,numero_compra);
CREATE UNIQUE INDEX venta_numero_diario ON ruizcacao.ventas(fecha_venta,numero_factura);
CREATE UNIQUE INDEX venta_comprobante ON ruizcacao.ventas(numero_comprobante);
ALTER TABLE ruizcacao.cuentas ADD CONSTRAINT titular_valido CHECK ((categoria='compra' AND proveedor_id IS NOT NULL AND cliente_id IS NULL) OR (categoria='venta' AND cliente_id IS NOT NULL AND proveedor_id IS NULL)), ADD CHECK(origen IN ('manual','compra','venta')), ADD CHECK(estado IN ('pendiente','parcial','cerrado','anulado')), ADD CHECK(monto_total>=0 AND monto_aplicado>=0);
ALTER TABLE ruizcacao.compras ADD CHECK(total>0 AND cantidad_qq>0 AND precio_compra_qq>0 AND monto_pagado_inicial BETWEEN 0 AND total), ADD CHECK(impuesto_porcentaje BETWEEN 0 AND 3);
ALTER TABLE ruizcacao.ventas ADD CHECK(total>0 AND cantidad_qq>0 AND precio_unitario>0), ADD CHECK(impuesto_porcentaje BETWEEN 0 AND 3);
ALTER TABLE ruizcacao.movimientos_cuenta ADD CHECK(monto>0), ADD CHECK(tipo IN ('Abono','Ajuste a favor','Ajuste por devolución')), ADD FOREIGN KEY(cliente_id) REFERENCES ruizcacao.clientes(id) DEFERRABLE INITIALLY DEFERRED, ADD FOREIGN KEY(proveedor_id) REFERENCES ruizcacao.proveedores(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ruizcacao.movimientos_stock ADD CHECK(entrada_qq>=0 AND salida_qq>=0 AND stock_resultante>=0), ADD FOREIGN KEY(proveedor_id) REFERENCES ruizcacao.proveedores(id) DEFERRABLE INITIALLY DEFERRED, ADD FOREIGN KEY(gasto_generado_id) REFERENCES ruizcacao.gastos(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ruizcacao.gastos ADD CHECK(tipo IN ('manual','automatico')), ADD FOREIGN KEY(referencia_stock_id) REFERENCES ruizcacao.movimientos_stock(id) DEFERRABLE INITIALLY DEFERRED, ADD FOREIGN KEY(proveedor_id) REFERENCES ruizcacao.proveedores(id) DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX movimientos_cuenta_cuenta_fecha ON ruizcacao.movimientos_cuenta(cuenta_id,fecha);
CREATE INDEX movimientos_stock_producto_fecha ON ruizcacao.movimientos_stock(producto,fecha);
CREATE INDEX gastos_fecha ON ruizcacao.gastos(fecha);
CREATE VIEW ruizcacao.v_saldos AS SELECT id,categoria,cliente_id,proveedor_id,monto_total,monto_aplicado,monto_total-monto_aplicado AS saldo FROM ruizcacao.cuentas WHERE estado<>'anulado';
CREATE VIEW ruizcacao.v_flujo_caja AS SELECT m.id,m.fecha,c.categoria,CASE WHEN c.categoria='compra' THEN -m.monto ELSE m.monto END AS monto FROM ruizcacao.movimientos_cuenta m JOIN ruizcacao.cuentas c ON c.id=m.cuenta_id WHERE m.tipo='Abono' AND c.estado<>'anulado' UNION ALL SELECT id,fecha,'gasto_operativo',-monto FROM ruizcacao.gastos WHERE tipo='manual';
COMMENT ON TABLE ruizcacao.existencias IS 'Saldo de inventario y costo promedio; actualizado atómicamente con los movimientos.';
COMMENT ON TABLE ruizcacao.operaciones IS 'Idempotencia de comandos: el JSON guarda la respuesta técnica para reintentos, no las entidades de negocio.';
COMMENT ON TABLE ruizcacao.auditoria IS 'Trazabilidad; el detalle JSON es una evidencia histórica, no la fuente de datos comerciales.';
COMMENT ON COLUMN ruizcacao.compras.proveedor_nombre IS 'Nombre histórico al registrar la compra.';
COMMENT ON COLUMN ruizcacao.movimientos_stock.diferencia_qq IS 'Resultado físico menos conversión; informativo según la regla actual del negocio.';
